# Generated by Django 3.2.3 on 2021-05-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRFApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Roll',
            new_name='roll',
        ),
    ]
